---
- hosts: workstation

  tasks:
    - name: install Alfred
      mac_pkg: pkg_type=app
               url=http://cachefly.alfredapp.com/Alfred_2.2_243b.zip
               archive_type=zip archive_path='Alfred 2.app'
      sudo: yes

