---
- hosts: workstation

  tasks:
    - name: "mk /tmp/.fonts dir"
      file: dest=/tmp/.fonts state=directory

    - name: clone powerline-fonts
      git: repo=https://github.com/OldhamMade/fonts
           dest=/tmp/.fonts/powerline

    - name: preparing to install powerline-fonts
      debug: msg="preparing to install"

    - name: install powerline-fonts
      sudo: true
      sudo_user: "{{ user }}"
      shell: "/tmp/.fonts/powerline/install.sh creates=~/Library/Fonts/Anonymice Powerline.ttf"
      register: result

    - debug: var=result

    - file: path="~/Library/Fonts/Anonymice Powerline.ttf" state=file
