---
- hosts: workstation

  tasks:
    - name: "mk $HOME/.fonts dir"
      file: dest=/tmp/.fonts state=directory
    - name: clone powerline-fonts
      git: repo=https://github.com/OldhamMade/fonts
           dest=/tmp/.fonts/powerline
    - name: install powerline-fonts
      script: "/tmp/.fonts/powerline/install.sh --home={{user_home}}
              creates={{user_home}}/Library/Fonts/Anonymice Powerline.ttf"
