---
- hosts: workstation

  tasks:
    - name: "mk $HOME/.fonts dir"
      file: dest=/tmp/.fonts state=directory
    - name: clone powerline-fonts
      git: repo=https://github.com/powerline/fonts
           dest=/tmp/.fonts/powerline
    - name: install powerline-fonts
      script: /tmp/.fonts/powerline/install.sh
              creates=/Library/Fonts/Anonymice Powerline.ttf
      tags:
        - debug
